# Generated by Django 3.2.5 on 2021-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
