# Generated by Django 3.2.5 on 2021-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCrud', '0002_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updateDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
